sudo: required
services:
  - docker

before_install:
  - docker build -t sohan0077/docker-test-ci -f Dockerfile.dev .

script:
  - docker run sohan0077/docker-test-ci npm run test -- --coverage --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "another-test"
  env: "Anothertest-env"
  bucket_name: "elasticbeanstalk-ap-south-1-806822280125"
  bucket_path: "another-test"
  edge: true
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
# Secret access key 1nlyhK2DKmGLDFY3OD5J9fyYktF2yWDnuX2XCAnh
# Access key ID AKIA3XWS27O6WURT3JZE
