sudo: required
services:
  - docker

before_install:
  - docker build -t sohan0077/docker-test-ci -f Dockerfile.dev .

script:
  - docker run sohan0077/docker-test-ci npm run test -- --coverage --watchAll=false
